development:
  cloud_name: <%= ENV.fetch("CLOUDINARY_CLOUD_NAME") %>
  api_key: <%= ENV.fetch("CLOUDINARY_API_KEY") %>
  api_secret: <%= ENV.fetch("CLOUDINARY_API_SECRET") %>
  secure: true

production:
  cloud_name: <%= ENV.fetch("CLOUDINARY_CLOUD_NAME") %>
  api_key: <%= ENV.fetch("CLOUDINARY_API_KEY") %>
  api_secret: <%= ENV.fetch("CLOUDINARY_API_SECRET") %>
  secure: true